--- drivers/misc/mediatek/usb20/Makefile
+++ drivers/misc/mediatek/usb20/Makefile
@@ -19,13 +19,13 @@ ifeq ($(MTK_ALPS_BOX_SUPPORT),yes)
 ccflags-y += -DMTK_ALPS_BOX_SUPPORT
 endif
 
-subdir-ccflags-$(CONFIG_ARCH_MT8127) += -DMUSB_PRE_CLOCK
-subdir-ccflags-$(CONFIG_ARCH_MT8163) += -DMUSB_PRE_CLOCK
-
 #QMU Flags
-ccflags-$(CONFIG_MTK_MUSB_QMU_SUPPORT) += -DMUSB_QMU_SUPPORT
-ccflags-$(CONFIG_MTK_MUSB_QMU_SUPPORT) += -DMUSB_QMU_SUPPORT_HOST
+subdir-ccflags-$(CONFIG_MTK_MUSB_QMU_SUPPORT) += -DMUSB_QMU_SUPPORT
+subdir-ccflags-$(CONFIG_MTK_MUSB_QMU_SUPPORT) += -DMUSB_QMU_SUPPORT_HOST
 ##ccflags-$(CONFIG_MTK_MUSB_QMU_SUPPORT) += -DQMU_TASKLET
+ifeq ($(CONFIG_MTK_MUSB_QMU_SUPPORT),y)
+subdir-ccflags-$(CONFIG_ARCH_MT8163) += -DMUSB_QMU_LIMIT_SUPPORT -DMUSB_QMU_LIMIT_RXQ_NUM=4 -DMUSB_QMU_LIMIT_TXQ_NUM=4
+endif
 
 ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat
 
