--- drivers/misc/mediatek/gpu/ged/Makefile
+++ drivers/misc/mediatek/gpu/ged/Makefile
@@ -63,17 +62,13 @@ endif
 endif
 # ---------------------- #
 
-$(info $$CONFIG_MTK_GPU_COMMON_DVFS_SUPPORT is [${CONFIG_MTK_GPU_COMMON_DVFS_SUPPORT}])
-    
+
 ifeq ($(CONFIG_MTK_GPU_COMMON_DVFS_SUPPORT),y)
-ccflags-y += -DGED_DVFS_ENABLE \
-             -DENABLE_COMMON_DVFS \
-	     -DENABLE_TIMER_BACKUP 
+ccflags-y += -DENABLE_COMMON_DVFS \
+	     -DENABLE_TIMER_BACKUP
 endif
 
-ifeq ($(CONFIG_MTK_FTRACE_DEFAULT_ENABLE),y)
-ccflags-y += -DENABLE_GED_SYSTRACE_UTIL
-endif
+ccflags-y += -DGED_SYSTRACE_UTIL
 
 ccflags-y += -DGED_DVFS_DEBUG_BUF
 
