--- drivers/misc/mediatek/power/mt6755/Makefile
+++ drivers/misc/mediatek/power/mt6755/Makefile
@@ -54,7 +54,11 @@ else
                           ifeq ($(CONFIG_MTK_BQ25896_SUPPORT),y)
                             obj-$(CONFIG_MTK_SMART_BATTERY) += bq25890.o charging_hw_bq25890.o
                           else
-			    obj-$(CONFIG_MTK_SMART_BATTERY) += charging_hw_pmic.o
+				ifeq ($(CONFIG_MTK_RT9466_SUPPORT),y)
+					obj-$(CONFIG_MTK_SMART_BATTERY) += rt9466.o
+				else
+					obj-$(CONFIG_MTK_SMART_BATTERY) += charging_hw_pmic.o
+				endif
                           endif
                     endif
                endif
