--- drivers/misc/mediatek/leds/Makefile
+++ drivers/misc/mediatek/leds/Makefile
@@ -1,7 +1,6 @@
 
 ccflags-y += -I$(srctree)/drivers/misc/mediatek/leds/$(MTK_PLATFORM)
 ccflags-y += -I$(srctree)/drivers/misc/mediatek/video/include
-ccflags-y += -I$(srctree)/drivers/misc/mediatek/pmic/include
 
 obj-$(CONFIG_MTK_LEDS) += leds_drv.o
 
