--- drivers/misc/mediatek/video/common/Makefile
+++ drivers/misc/mediatek/video/common/Makefile
@@ -39,7 +39,7 @@
 obj-$(CONFIG_MTK_FB) += 	mtkfb_fence.o \
 				fbconfig_kdebug.o
 
-ifeq (y, $(filter y, $(CONFIG_ARCH_MT6735) $(CONFIG_ARCH_MT6735M) $(CONFIG_ARCH_MT6753) $(CONFIG_ARCH_MT6570) $(CONFIG_ARCH_MT6580) $(CONFIG_ARCH_MT6797)))
+ifeq (y, $(filter y, $(CONFIG_ARCH_MT6735) $(CONFIG_ARCH_MT6735M) $(CONFIG_ARCH_MT6753) $(CONFIG_ARCH_MT6580) $(CONFIG_ARCH_MT6797)))
 obj-$(CONFIG_MTK_FB) += mtkfb.o
 endif
 
@@ -124,3 +124,8 @@ endif
 ifeq ($(CONFIG_MTK_DITHERING_SUPPORT), y)
 ccflags-y += -DDITHERING_SUPPORT
 endif
+
+ifeq (y, $(filter y, $(CONFIG_ARCH_MT6755)))
+obj-y += layering_rule_base/v1/
+endif
+
