--- drivers/misc/mediatek/pmic/Makefile
+++ drivers/misc/mediatek/pmic/Makefile
@@ -8,5 +8,6 @@ obj-$(CONFIG_MTK_PMIC_CHIP_MT6336) += mt6336/
 obj-$(CONFIG_MTK_PMIC_CHIP_MT6337) += mt6337/
 obj-$(CONFIG_MTK_PMIC_CHIP_MT6353) += mt6353/
 
-obj-$(CONFIG_MFD_RT5081_PMU)	+= rt5081/
 obj-$(CONFIG_MTK_AUXADC_INTF)   += mtk_auxadc_intf.o
+
+obj-$(CONFIG_MFD_RT5081A_PMU)    += rt5081a/
